-- mysql -u root -p
CREATE DATABASE Test;
USE Test;

CREATE TABLE Users (
    id INT(15) NOT NULL PRIMARY KEY AUTO_INCREMENT, AUTO_INCREMENT = 1,
    username VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(300) NOT NULL
);

ALTER TABLE Users
    ADD PRIMARY KEY (id);

ALTER TABLE Users
    MODIFY id INT(15) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;

ALTER TABLE Users MODIFY password VARCHAR NOT NULL;

ALTER TABLE Users MODIFY password VARCHAR NOT NULL;

CREATE TABLE IF NOT EXISTS Users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    UNIQUE KEY (username)
)ENGINE=InnoDB AUTO_INCREMENT=1 COMMENT='Tabla de Usuarios';


-- PRODUCTOS
CREATE TABLE IF NOT EXISTS Productos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50)
);

DESCRIBE Users;
